spring:
  application:
    name: @project.artifactId@
  jpa:
    hibernate:
      # schema is managed by Flyway, only validate
      ddl-auto: validate
  flyway:
    locations:
      - classpath:db/migration/schema
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences:
          # adds audience verification - https://docs.spring.io/spring-security/reference/servlet/oauth2/resource-server/jwt.html#_supplying_audiences
          # requires client to be in audience claim, see https://www.keycloak.org/docs/latest/server_admin/#_audience_resolve
          # TODO - should be the clientId of the actual project
          - refarch

server:
  error:
    whitelabel:
      enabled: false

# Config for spring actuator endpoints
management:
  endpoints:
    access:
      default: none
    web:
      exposure:
        include: health, info, prometheus
      path-mapping:
        prometheus: metrics
  endpoint:
    health:
      access: read_only
      probes:
        enabled: true
    info:
      access: read_only
    prometheus:
      access: read_only
  info:
    env:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

info:
  application:
    name: @project.artifactId@
    version: @project.version@
    description: @project.description@
  build:
    java.version: @java.version@
    spring-cloud.version: @spring-cloud-dependencies.version@