/* tslint:disable */
/* eslint-disable */
/**
 * refarch-backend
 * This is the default starting project for a backend project based on the reference architecture of it@M
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TheEntityRequestDTO
 */
export interface TheEntityRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof TheEntityRequestDTO
     */
    textAttribute: string;
}

/**
 * Check if a given object implements the TheEntityRequestDTO interface.
 */
export function instanceOfTheEntityRequestDTO(value: object): value is TheEntityRequestDTO {
    if (!('textAttribute' in value) || value['textAttribute'] === undefined) return false;
    return true;
}

export function TheEntityRequestDTOFromJSON(json: any): TheEntityRequestDTO {
    return TheEntityRequestDTOFromJSONTyped(json, false);
}

export function TheEntityRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TheEntityRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'textAttribute': json['textAttribute'],
    };
}

export function TheEntityRequestDTOToJSON(json: any): TheEntityRequestDTO {
    return TheEntityRequestDTOToJSONTyped(json, false);
}

export function TheEntityRequestDTOToJSONTyped(value?: TheEntityRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'textAttribute': value['textAttribute'],
    };
}

