/* tslint:disable */
/* eslint-disable */
/**
 * refarch-backend
 * This is the default starting project for a backend project based on the reference architecture of it@M
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Link,
} from '../models/index';
import {
    LinkFromJSON,
    LinkToJSON,
} from '../models/index';

export interface SbomRequest {
    id: string;
}

export interface ScrapeRequest {
    format?: ScrapeFormatEnum;
    includedNames?: string;
}

/**
 * 
 */
export class ActuatorApi extends runtime.BaseAPI {

    /**
     * Actuator web endpoint \'health\'
     */
    async healthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/actuator/health`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Actuator web endpoint \'health\'
     */
    async health(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.healthRaw(initOverrides);
        return await response.value();
    }

    /**
     * Actuator web endpoint \'info\'
     */
    async infoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/actuator/info`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Actuator web endpoint \'info\'
     */
    async info(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.infoRaw(initOverrides);
        return await response.value();
    }

    /**
     * Actuator root web endpoint
     */
    async linksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: { [key: string]: Link; }; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/actuator`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Actuator root web endpoint
     */
    async links(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: { [key: string]: Link; }; }> {
        const response = await this.linksRaw(initOverrides);
        return await response.value();
    }

    /**
     * Actuator web endpoint \'sbom-id\'
     */
    async sbomRaw(requestParameters: SbomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling sbom().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/actuator/sbom/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Actuator web endpoint \'sbom-id\'
     */
    async sbom(requestParameters: SbomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.sbomRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Actuator web endpoint \'sbom\'
     */
    async sbomsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/actuator/sbom`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Actuator web endpoint \'sbom\'
     */
    async sboms(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.sbomsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Actuator web endpoint \'prometheus\'
     */
    async scrapeRaw(requestParameters: ScrapeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        if (requestParameters['includedNames'] != null) {
            queryParameters['includedNames'] = requestParameters['includedNames'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/actuator/metrics`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Actuator web endpoint \'prometheus\'
     */
    async scrape(requestParameters: ScrapeRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.scrapeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ScrapeFormatEnum = {
    CONTENT_TYPE_004: 'CONTENT_TYPE_004',
    CONTENT_TYPE_OPENMETRICS_100: 'CONTENT_TYPE_OPENMETRICS_100',
    CONTENT_TYPE_PROTOBUF: 'CONTENT_TYPE_PROTOBUF'
} as const;
export type ScrapeFormatEnum = typeof ScrapeFormatEnum[keyof typeof ScrapeFormatEnum];
