spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.security.oauth2.gateway.TokenRelayAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.client.reactive.ReactiveOAuth2ClientAutoConfiguration
  cloud:
    gateway:
      # The whole list need to be overridden to remove CustomTokenRelayGatewayFilter
      default-filters:
        - RemoveResponseHeader=Expires
        - RemoveRequestHeader=cookie
        - RemoveRequestHeader=x-xsrf-token

