appswitcher.apps:
  pgadmin:
    display-name: pgAdmin
    url: http://localhost:5050
    image-url: https://upload.wikimedia.org/wikipedia/commons/a/ad/Logo_PostgreSQL.png
    tags:
      - global
  keycloak:
    display-name: Keycloak
    url: http://localhost:8100/auth/admin
    image-url: https://upload.wikimedia.org/wikipedia/commons/2/29/Keycloak_Logo.png
    tags:
      - global
