# Workflow for scanning GitHub workflows with actionlint
name: actionlint

on:
  pull_request:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # needed to annotate the files in a pull request with comments
      pull-requests: write
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-actionlint@bcd2cb2a470e6de82ba45ce9ede3d2f43560c58a # v1.5.0
