# Workflow for building NPM/Maven projects and Docker images
name: build

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  # JOB to run change detection
  build-check-changed-files:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    outputs:
      # Expose matched filters as job 'packages' output variable
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-checkout@4ed8f906bab8111fbd9a7af8e3f4129f9b721757 # v1.2.3
      # For pull requests it's not necessary to checkout the code
      - uses: it-at-m/lhm_actions/action-templates/actions/action-filter@4ed8f906bab8111fbd9a7af8e3f4129f9b721757 # v1.2.3
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            backend: 
              - backend/**
              - .github/workflows/build.yml
            frontend: 
              - frontend/**
              - backend/api-spec/**
              - .github/workflows/build.yml
            webcomponent: 
              - webcomponent/**
              - backend/api-spec/**
              - .github/workflows/build.yml
            eai: 
              - eai/**
              - .github/workflows/build.yml
      - run: |
          echo ${{ toJSON(steps.filter.outputs.changes) }}
  build:
    if: ${{ needs.build-check-changed-files.outputs.packages != '' && needs.build-check-changed-files.outputs.packages != '[]' }}
    needs: build-check-changed-files
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        app-path: ${{ fromJSON(needs.build-check-changed-files.outputs.packages) }}
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-checkout@4ed8f906bab8111fbd9a7af8e3f4129f9b721757 # v1.2.3
      - id: node # required for steps.* syntax
        if: ${{ hashFiles(format('./{0}/package.json', matrix.app-path)) != '' }}
        uses: it-at-m/lhm_actions/action-templates/actions/action-npm-build@4ed8f906bab8111fbd9a7af8e3f4129f9b721757 # v1.2.3
        with:
          app-path: ${{ matrix.app-path }}
      - id: maven # required for steps.* syntax
        if: ${{ hashFiles(format('./{0}/pom.xml', matrix.app-path)) != '' }}
        uses: it-at-m/lhm_actions/action-templates/actions/action-maven-build@4ed8f906bab8111fbd9a7af8e3f4129f9b721757 # v1.2.3
        with:
          app-path: ${{ matrix.app-path }}
      - if: ${{ github.ref == 'refs/heads/main' && (steps.node.outcome == 'success' || steps.maven.outcome == 'success') && hashFiles(format('./{0}/Dockerfile', matrix.app-path)) != '' }}
        uses: it-at-m/lhm_actions/action-templates/actions/action-build-image@4ed8f906bab8111fbd9a7af8e3f4129f9b721757 # v1.2.3
        with:
          path: ${{ matrix.app-path }}
          image-name: ${{ matrix.app-path }}
          artifact-name: ${{ join(steps.*.outputs.artifact-name) }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          registry-username: ${{ github.actor }}
          image-tags: |
            type=raw,value=dev
