# Workflow for building NPM/Maven projects and Docker images
name: build

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      TZ: Europe/Berlin
    strategy:
      fail-fast: false
      matrix:
        include: # Add or modify paths according to your project structure
          - app-path: backend
          - app-path: frontend
          - app-path: eai
          - app-path: webcomponent

    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-checkout@94f7e40aa557a2790abfa98a9cc9186d260b94f8 # v1.0.27
      - id: node # required for steps.* syntax
        if: ${{ hashFiles(format('./{0}/package.json', matrix.app-path)) != '' }}
        uses: it-at-m/lhm_actions/action-templates/actions/action-npm-build@94f7e40aa557a2790abfa98a9cc9186d260b94f8 # v1.0.27
        with:
          app-path: ${{ matrix.app-path }}
          node-version: "24"
      - id: maven # required for steps.* syntax
        if: ${{ hashFiles(format('./{0}/pom.xml', matrix.app-path)) != '' }}
        uses: it-at-m/lhm_actions/action-templates/actions/action-maven-build@94f7e40aa557a2790abfa98a9cc9186d260b94f8 # v1.0.27
        with:
          app-path: ${{ matrix.app-path }}
          java-version: "25"
      - if: ${{ github.ref == 'refs/heads/main' && (steps.node.outcome == 'success' || steps.maven.outcome == 'success') }}
        uses: it-at-m/lhm_actions/action-templates/actions/action-build-image@94f7e40aa557a2790abfa98a9cc9186d260b94f8 # v1.0.27
        with:
          path: ${{ matrix.app-path }}
          image-name: ${{ matrix.app-path }}
          artifact-name: ${{ join(steps.*.outputs.artifact-name) }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          registry-username: ${{ github.actor }}
          image-tags: |
            type=raw,value=dev
