# Workflow for building NPM/Maven projects and Docker images
name: build

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    outputs:
      # Expose matched filters as job 'packages' output variable
      packages: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: it-at-m/lhm_actions/action-templates/actions/action-checkout@94f7e40aa557a2790abfa98a9cc9186d260b94f8 # v1.0.27
    # For pull requests it's not necessary to checkout the code
    - uses: it-at-m/lhm_actions/action-templates/actions/action-filter@6db6885319cb1f85f75cd2947caa96596047711b # v1.1.0
      id: filter
      with:
        base: ${{ github.ref }}    
        filters: |
          backend: 
           - backend/**
           - .github/workflows/build.yml
          frontend: 
           - frontend/**
           - .github/**
          webcomponent: 
           - webcomponent/**
           - .github/workflows/build.yml
          eai: 
           - eai/**
           - .github/workflows/build.yml
    - run: |
        echo ${{ toJSON(steps.filter.outputs.changes) }}
  build:
    if: ${{ needs.changes.outputs.packages != '' && needs.changes.outputs.packages != '[]' }}
    needs: changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      TZ: Europe/Berlin
    strategy:
      fail-fast: false
      matrix:
        app-path: ${{ fromJSON(needs.changes.outputs.packages) }}

    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-checkout@699d5d46ed8bcce2227e2d58101d1dde7a713d53 # v1.2.0
      - id: node # required for steps.* syntax
        if: ${{ hashFiles(format('./{0}/package.json', matrix.app-path)) != '' }}
        uses: it-at-m/lhm_actions/action-templates/actions/action-npm-build@699d5d46ed8bcce2227e2d58101d1dde7a713d53 # v1.2.0
        with:
          app-path: ${{ matrix.app-path }}
          node-version: "24"
      - id: maven # required for steps.* syntax
        if: ${{ hashFiles(format('./{0}/pom.xml', matrix.app-path)) != '' }}
        uses: it-at-m/lhm_actions/action-templates/actions/action-maven-build@699d5d46ed8bcce2227e2d58101d1dde7a713d53 # v1.2.0
        with:
          app-path: ${{ matrix.app-path }}
          java-version: "21"
      - if: ${{ github.ref == 'refs/heads/main' && (steps.node.outcome == 'success' || steps.maven.outcome == 'success') }}
        uses: it-at-m/lhm_actions/action-templates/actions/action-build-image@699d5d46ed8bcce2227e2d58101d1dde7a713d53 # v1.2.0
        with:
          path: ${{ matrix.app-path }}
          image-name: ${{ matrix.app-path }}
          artifact-name: ${{ join(steps.*.outputs.artifact-name) }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          registry-username: ${{ github.actor }}
          image-tags: |
            type=raw,value=dev
