# Workflow that runs license check for used dependencies
name: dependency-review

on:
  pull_request:

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-dependency-review@acb09213786b76dd7aa52ec1d901390d28c60eb0 # v1.0.29
