# Workflow that runs license check for used dependencies
name: dependency-review

on:
  pull_request:

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-dependency-review@7768a71df3e9e50ca240e2a69a31c4910e1a8ea0 # v1.0.31
