# Sample workflow for building and deploying a VitePress site to GitHub Pages
#
name: Deploy VitePress site to Pages

on:
  # Runs on pushes targeting the `main` branch. Change this to `master` if you're
  # using the `master` branch as the default branch.
  push:
    branches: [main]
    paths:
      - "docs/**"
      - ".github/workflows/**" # define the concrete paths on which a change triggers this action, e.g. backend/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-pages:
    uses: it-at-m/.github/.github/workflows/reuseable-template-deploy-pages.yml@main
