# Workflow to check health of dockercompose based development stacks
name: dockercompose-healthcheck

on:
  pull_request:

jobs:
  dockercompose-healthcheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-dockercompose-healthcheck@4ed8f906bab8111fbd9a7af8e3f4129f9b721757 # v1.2.3
        with:
          skip-exited: true # required for keycloakmigration init container
          compose-file-path: "./stack/"
