# Workflow to check health of dockercompose based development stacks
name: dockercompose-healthcheck

on:
  pull_request:

jobs:
  dockercompose-healthcheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-dockercompose-healthcheck@e9a8422d740d4e9eaef25cfeeb3a5790da97a7aa # v1.2.4
        with:
          skip-exited: true # required for keycloakmigration init container
          compose-file-path: "./stack/"
