# Workflow to check health of dockercompose based development stacks
name: dockercompose-healthcheck

on:
  pull_request:

jobs:
  dockercompose-healthcheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-dockercompose-healthcheck@6db6885319cb1f85f75cd2947caa96596047711b # v1.1.0
        with:
          skip-exited: true # required for keycloakmigration init container
          compose-file-path: "./stack/"
