name: Build all

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      TZ: Europe/Berlin # timezone
    strategy:
      fail-fast: false
      matrix:
        include: # hier müssen die Pfade angegeben werden
          - app-path: refarch-backend
          - app-path: refarch-frontend
          - app-path: refarch-eai
          - app-path: refarch-webcomponent

    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-checkout@992204b33cb6a9766bbc8bc57ccd1460c4bf1aa9 # v1.0.26
      - if: ${{ hashFiles(format('./{0}/package.json', matrix.app-path))!=null }}
        id: node
        uses: it-at-m/lhm_actions/action-templates/actions/action-npm-build@992204b33cb6a9766bbc8bc57ccd1460c4bf1aa9 # v1.0.26
        with:
          app-path: ${{ matrix.app-path }}
          node-version: "24"
      - if: ${{ hashFiles(format('./{0}/pom.xml', matrix.app-path))!=null }}
        id: maven
        uses: it-at-m/lhm_actions/action-templates/actions/action-maven-build@992204b33cb6a9766bbc8bc57ccd1460c4bf1aa9 # v1.0.26
        with:
          app-path: ${{ matrix.app-path }}
          java-version: "21"
      - if: github.ref == 'refs/heads/main'
        uses: it-at-m/lhm_actions/action-templates/actions/action-build-image@992204b33cb6a9766bbc8bc57ccd1460c4bf1aa9 # v1.0.26
        with:
          path: ${{ matrix.app-path }}
          image-name: ${{ matrix.app-path }}
          artifact-name: ${{ join(steps.*.outputs.artifact-name) }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          registry-username: ${{ github.actor }}
          image-tags: |
            type=raw,value=dev
