name: Require PR Checklist

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]

jobs:
  pr-checklist:
    runs-on: ubuntu-latest
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-pr-checklist@a4dd26733adc7d71b10fbd744ef355c01e4b7040 # v1.0.8