name: Label PRs
on:
  - pull_request_target

jobs:
  pr-labeler:
    permissions:
      contents: read
      pull-requests: write
      issues: write # permission to create labels if not exist
    runs-on: ubuntu-latest
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-pr-labeler@992204b33cb6a9766bbc8bc57ccd1460c4bf1aa9 # v1.0.26
