name: "pr-labeler"
on:
  - pull_request_target

jobs:
  pr-labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: "Label PR"
        uses: it-at-m/lhm_actions/action-templates/actions/action-pr-labeler@7757eb7f3c158d5f7935b08ff581b395a89d39ee # v1.0.6