# Workflow to assign appropriate labels to PRs
name: pr-labeler
on:
  - pull_request_target

jobs:
  pr-labeler:
    permissions:
      contents: read
      pull-requests: write
      issues: write # permission to create labels if not exist
    runs-on: ubuntu-latest
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-pr-labeler@bcd2cb2a470e6de82ba45ce9ede3d2f43560c58a # v1.5.0
