name: Label PRs
on:
  - pull_request_target

jobs:
  pr-labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-pr-labeler@b2b49a8b4344e3b5ac90dd1ee9a0c59860c41383 # v1.0.16
