name: "pr-labeler"
on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: "Label PR"
        uses: actions/labeler@v5
        with:
          sync-labels: true