# Workflow to release Maven-based artifacts
name: release-maven

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: "Version to use when preparing a release (e.g., 1.2.3)"
        required: true
        default: "X.Y.Z"
      development-version:
        description: "Version to use for new local working copy (e.g., 1.2.4-SNAPSHOT)"
        required: true
        default: X.Y.Z-SNAPSHOT
      app-path:
        type: choice
        description: Service-Name
        required: true
        options: # Add or modify paths according to your project structure
          - backend
          - eai

jobs:
  release-maven-artifact:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write # must be removed if use-pr is 'false'
    outputs:
      MVN_ARTIFACT_ID: ${{ steps.release-maven-artifact.outputs.MVN_ARTIFACT_ID }}
      ARTIFACT_NAME: ${{ steps.release-maven-artifact.outputs.artifact-name }}
    steps:
      - id: release-maven-artifact
        uses: it-at-m/lhm_actions/action-templates/actions/action-maven-release@4ed8f906bab8111fbd9a7af8e3f4129f9b721757 # v1.2.3
        with:
          app-path: ${{ inputs.app-path }}
          releaseVersion: ${{ inputs.release-version }}
          developmentVersion: ${{ inputs.development-version }}
          use-pr: "true"
          # the following variables are necessary to publish the packages to maven central
          # docs: https://it-at-m.github.io/lhm_actions/workflows.html#maven-central
          # skipDeployment: false
          # SIGN_KEY_PASS: ${{ secrets.gpg_passphrase }}
          # CENTRAL_USERNAME: ${{ secrets.sonatype_username }}
          # CENTRAL_PASSWORD: ${{ secrets.sonatype_password }}
          # GPG_PRIVATE_KEY: ${{ secrets.gpg_private_key }}

  release-maven-image:
    runs-on: ubuntu-latest
    needs: release-maven-artifact
    permissions:
      packages: write
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-build-image@4ed8f906bab8111fbd9a7af8e3f4129f9b721757 # v1.2.3
        with:
          path: ${{ inputs.app-path }}
          artifact-name: ${{ needs.release-maven-artifact.outputs.ARTIFACT_NAME }}
          image-name: ${{ inputs.app-path }}
          image-tags: |
            type=semver,pattern={{version}},value=${{ inputs.release-version }}
            type=raw,value=latest
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}

  release-maven-github:
    needs: [release-maven-artifact, release-maven-image]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-create-github-release@4ed8f906bab8111fbd9a7af8e3f4129f9b721757 # v1.2.3
        with:
          artifact-name: ${{ needs.release-maven-artifact.outputs.ARTIFACT_NAME }}
          artifact-path: ${{ inputs.app-path }}/target/*.jar
          tag-name: ${{ inputs.app-path }}-${{ inputs.release-version }}
          generate-release-notes: true