# Workflow to release NPM-based artifacts
name: release-npm

on:
  workflow_dispatch:
    inputs:
      release-version:
        type: choice
        description: "Select version increment type (follows Semantic Versioning)"
        required: true
        options:
          - patch
          - minor
          - major
      app-path:
        type: choice
        description: "Select the node service to release"
        required: true
        default: frontend
        options: # Add or modify paths according to your project structure
          - frontend
          - webcomponent
          
jobs:
  release-npm-artifact:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write # can be removed if use-pr is 'false'
      # id-token: write # required when publishing with `npm publish --provenance`
    outputs:
      ARTIFACT_NAME: ${{ steps.build.outputs.artifact-name }}
      ARTIFACT_VERSION: ${{ steps.release-npm-artifact.outputs.ARTIFACT_VERSION }}
    steps:
      - id: release-npm-artifact
        uses: it-at-m/lhm_actions/action-templates/actions/action-npm-release@b088b94cad35e50b197104c9e2ac8fb25a7116b3 # v1.0.33
        with:
          app-path: ${{ inputs.app-path }}
          node-version: "24"
          releaseVersion: ${{ inputs.release-version }}
          use-pr: "true"
      - id: build
        uses: it-at-m/lhm_actions/action-templates/actions/action-npm-build@b088b94cad35e50b197104c9e2ac8fb25a7116b3 # v1.0.33
        with:
          app-path: ${{ inputs.app-path }}
          node-version: "24"
      # necessary to publish to npm registry
      # - id: publish
      #   shell: bash
      #   working-directory: ./${{ inputs.app-path }}
      #   run: npm publish --provenance --access public

  release-npm-image:
    needs: release-npm-artifact
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-build-image@b088b94cad35e50b197104c9e2ac8fb25a7116b3 # v1.0.33
        with:
          path: ${{ inputs.app-path }}
          image-name: ${{ inputs.app-path }}
          artifact-name: ${{ needs.release-npm-artifact.outputs.ARTIFACT_NAME }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          registry-username: ${{ github.actor }}
          image-tags: |
            type=semver,pattern={{version}},value=${{ needs.release-npm-artifact.outputs.ARTIFACT_VERSION }}
            type=raw,value=latest

  release-npm-github:
    needs: release-npm-artifact
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-create-github-release@b088b94cad35e50b197104c9e2ac8fb25a7116b3 # v1.0.33
        with:
          artifact-name: ${{ needs.release-npm-artifact.outputs.ARTIFACT_NAME }}
          tag-name: ${{ inputs.app-path }}-${{ needs.release-npm-artifact.outputs.ARTIFACT_VERSION }}
