# Workflow for running security scan using Trivy
name: trivy

on:
  pull_request:
  schedule:
    - cron: '0 3 * * *' # Daily at 03:00 UTC

jobs:
  trivy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # Required to upload SARIF results to the GitHub Security tab
    if: github.event_name == 'schedule' 
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-trivy@6db6885319cb1f85f75cd2947caa96596047711b # v1.1.0
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    if: github.event_name == 'pull_request' 
    outputs:
      # Expose matched filters as job 'packages' output variable
      packages: ${{ steps.filter.outputs.changes }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: it-at-m/lhm_actions/action-templates/actions/action-filter@6db6885319cb1f85f75cd2947caa96596047711b # v1.1.0
      id: filter
      with:
        filters: |
          docs: docs/**
          backend: backend/**
          frontend: frontend/**
          webcomponent: webcomponent/**
          eai: eai/**
    - run: |
        echo ${{ toJSON(steps.filter.outputs.changes) }}
        
  # JOB to find out modified packages
  trivy-partial:
    needs: changes
    if:  ${{ needs.changes.outputs.packages != '[]' && needs.changes.outputs.packages != '' }} 
    strategy:
      matrix:
        # Parse JSON array containing names of all filters matching any of changed files
        # e.g. ['package1', 'package2'] if both package folders contains changes
        package: ${{ fromJSON(needs.changes.outputs.packages) [0] && fromJSON(needs.changes.outputs.packages) || fromJSON('["skip"]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-trivy@6db6885319cb1f85f75cd2947caa96596047711b # v1.1.0
        with:
          path: ${{ matrix.package }}
