name: Trivy security scan
on:
  pull_request:
  schedule:
    - cron: '0 3 * * *' # Daily at 03:00 UTC
jobs:
  scan:
    name: Security check
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule' || github.ref == 'refs/heads/main'
    steps:
      - name: Run Trivy security check on repository
        uses: it-at-m/lhm_actions/action-templates/actions/action-trivy@7cb754b2056cebda6c36db344434f85be398c493 # v1.0.25
