name: Trivy security scan
on:
  pull_request:
  schedule:
    - cron: '0 3 * * *' # Daily at 03:00 UTC
jobs:
  scan:
    name: Security check
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule' || github.ref == 'refs/heads/main'
    steps:
      - name: Run Trivy security check on repository
        uses: it-at-m/lhm_actions/action-templates/actions/action-trivy@93bc0588b20f51660a827470790f6e52b7e300e6
