/* tslint:disable */
/* eslint-disable */
/**
 * refarch-backend
 * This is the default starting project for a backend project based on the reference architecture of it@M
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { TheEntityResponseDTO } from './TheEntityResponseDTO';
import {
    TheEntityResponseDTOFromJSON,
    TheEntityResponseDTOFromJSONTyped,
    TheEntityResponseDTOToJSON,
    TheEntityResponseDTOToJSONTyped,
} from './TheEntityResponseDTO';

/**
 * 
 * @export
 * @interface PagedModelTheEntityResponseDTO
 */
export interface PagedModelTheEntityResponseDTO {
    /**
     * 
     * @type {Array<TheEntityResponseDTO>}
     * @memberof PagedModelTheEntityResponseDTO
     */
    content?: Array<TheEntityResponseDTO>;
    /**
     * 
     * @type {PageMetadata}
     * @memberof PagedModelTheEntityResponseDTO
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the PagedModelTheEntityResponseDTO interface.
 */
export function instanceOfPagedModelTheEntityResponseDTO(value: object): value is PagedModelTheEntityResponseDTO {
    return true;
}

export function PagedModelTheEntityResponseDTOFromJSON(json: any): PagedModelTheEntityResponseDTO {
    return PagedModelTheEntityResponseDTOFromJSONTyped(json, false);
}

export function PagedModelTheEntityResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelTheEntityResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(TheEntityResponseDTOFromJSON)),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function PagedModelTheEntityResponseDTOToJSON(json: any): PagedModelTheEntityResponseDTO {
    return PagedModelTheEntityResponseDTOToJSONTyped(json, false);
}

export function PagedModelTheEntityResponseDTOToJSONTyped(value?: PagedModelTheEntityResponseDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(TheEntityResponseDTOToJSON)),
        'page': PageMetadataToJSON(value['page']),
    };
}

