/* tslint:disable */
/* eslint-disable */
/**
 * refarch-backend
 * This is the default starting project for a backend project based on the reference architecture of it@M
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TheEntityResponseDTO
 */
export interface TheEntityResponseDTO {
    /**
     * 
     * @type {string}
     * @memberof TheEntityResponseDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TheEntityResponseDTO
     */
    textAttribute?: string;
}

/**
 * Check if a given object implements the TheEntityResponseDTO interface.
 */
export function instanceOfTheEntityResponseDTO(value: object): value is TheEntityResponseDTO {
    return true;
}

export function TheEntityResponseDTOFromJSON(json: any): TheEntityResponseDTO {
    return TheEntityResponseDTOFromJSONTyped(json, false);
}

export function TheEntityResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TheEntityResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'textAttribute': json['textAttribute'] == null ? undefined : json['textAttribute'],
    };
}

export function TheEntityResponseDTOToJSON(json: any): TheEntityResponseDTO {
    return TheEntityResponseDTOToJSONTyped(json, false);
}

export function TheEntityResponseDTOToJSONTyped(value?: TheEntityResponseDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'textAttribute': value['textAttribute'],
    };
}

